#!/bin/bash

DESC="Compojure"
NAME="nakkaya.com"

NOHUP="nohup"
JAVA="java"
OPTS="-Dfile.encoding=UTF-8"
JARFOLDER="lib/"
PID_FILE="comp.pid"
ROUTES="src/nakkaya/core.clj"

## build jar list
JARS="-cp ./src/:"

for i in `find $JARFOLDER -name *.jar`
do
    JARS=${JARS}:${i}
done

JVM_OPTS="-Dcompojure.site=\"$NAME\" "

for opts in "$@"
do
    case "$opts" in
	no-cache)
	    JVM_OPTS=${JVM_OPTS}"-Dcompojure.cache=\"off\" "
	    ;;
    esac
done

d_start(){
    if [ -e $PID_FILE ] 
    then
     	PID=$(cat $PID_FILE)
    	if ps -p $PID > /dev/null
    	then 
    	    echo "$NAME already running.."
    	    exit 0
    	fi
    fi

    $NOHUP $JAVA $OPTS $JVM_OPTS $JARS clojure.main $ROUTES &
    COMPOJURE_PID=$!
    echo $COMPOJURE_PID > $PID_FILE
}

d_stop(){
    if [ -e $PID_FILE ] 
    then
	COMPOJURE_PID=$(cat $PID_FILE)
	kill $COMPOJURE_PID
	rm $PID_FILE
    else
    	echo "$NAME is not running.."
    fi
}

case "$1" in
    start)
	echo "Starting $DESC: $NAME"
	d_start
	;;
    stop)
	echo "Stopping $DESC: $NAME"
	d_stop
	;;
    *)
	echo "Usage: compctl {start|stop}"
	exit 1
	;;
esac

exit 0
