#+title: Clodiuno - Clojure API for Arduino
#+tags: clojure clodiuno arduino
#+description: Clodiuno is a Clojure API for Arduino.

Clodiuno is a library that allows you to control Arduino using Clojure
allowing Clojure developers to interface with real world using Arduino
hardware.

Currently Clodiuno supports two interfaces, you can either use the USB
connection via Firmata or you can connect to your Arduino using WiFi via
WiShield.

*** Dependencies (Firmata)

Firmata is a serial binary protocol, to get Java communicate via Serial
Port there are two options, [[http://java.sun.com/products/javacomm/][JavaComm]] API and [[http://users.frii.com/jarvi/rxtx/][rxtx]] API. Clodiuno uses rxtx,
because thats what Arduino IDE uses, you already have the Jars required
installed with your Arduino installation.

From your Arduino installation copy,

 - RXTXcomm.jar
 - librxtxSerial.jnilib (OS X Users)
 - librxtxSerial.dll (Windows Users)
 - librxtxSerial.so (Linux Users)

into your Java extensions folder, if you choose to place the Jars
somewhere else make sure to set your Java library path to point to that
folder too.

For Mac OS X users they are located inside the application bundle,

#+begin_example
   open /Applications/Arduino.app/Contents/Resources/Java/
#+end_example

Also if you are on Mac OS X, make sure you use 32 bit Java,
otherwise RXTX won't work.

*** Dependencies (WiShield)

None.

*** Installation

Clodiuno is also available via [[http://clojars.org/clodiuno][Clojars]], for now only Mac OS X native
dependencies are available on clojars.

#+begin_src clojure
  (defproject arduino-project "1.0.0-SNAPSHOT"
    :dependencies [[org.clojure/clojure "1.2.0"]
                   [org.clojure/clojure-contrib "1.2.0"]
                   [clodiuno "0.0.3-SNAPSHOT"]]
    :native-dependencies [[org.clojars.nakkaya/rxtx-macosx-native-deps "2.1.7"]]
    :dev-dependencies [[native-deps "1.0.5"]]
    :jvm-opts ["-Djava.library.path=./native/macosx/x86/"
               "-d32"
               "-server"])
#+end_src

*** For Firmata Interface

You need to upload Firmata sketch to your Arduino, 

#+begin_example
   File -> Examples -> Firmata -> StandartFirmata
#+end_example

*** For WiShield Interface

Make sure [[http://asynclabs.com/wiki/index.php?title=AsyncLabsWiki][WiShield]] library is configured to compile and run [[http://asynclabs.com/wiki/index.php?title=SocketApp_sketch][SocketApp]]
sketch, once configured you can upload the wishield sketch located in
the resources folder.

*** Usage

resources/examples/ folder contains  examples to give a feel for the
API, I also have the following hacks using Clodiuno,

 - [[/2010/01/03/clodiuno-a-clojure-api-for-the-firmata-protocol/][Blinking SOS]]
 - [[/2010/01/06/making-things-move-with-clojure/][Servo Control]]
 - [[/2010/02/02/etch-a-sketch/][Etch A Sketch]]
 - [[/2010/05/21/motor-control-via-esc-using-arduino-and-clodiuno/][ESC Control]]
 - [[/2010/06/04/motor-control-via-ardumoto-using-arduino-and-clodiuno/][Ardumoto Control]]
 - [[/2010/08/09/wishield-support-for-clodiuno/][Using WiShield and Firmata Together]]
 - [[/2010/09/28/clodiuno-processing-adxl335-accelerometer/][Clodiuno/Processing ADXL335 Accelerometer]]
 - [[/2011/01/04/duck-hunt-experiment/][Duck Hunt Experiment]]

*** Source

Project is hosted at github, grab it [[http://github.com/nakkaya/clodiuno][here]].

*** License

Beerware Revision 42
